%feature("docstring") OT::ActiveLearningGMMFunction
R"RAW(Active learning criterion for reliability analysis implementing the Generalized Max Min function.

Parameters
----------
reliabilityThreshold : float
    Reliability analysis threshold.

learningThreshold : float
    Threshold used to check the active learning convergence.
    
inputDistribution : Distribution
    Probability distribution of the input variables.

outputQuantileLevel : float
    Quantile level of the samples that will be considered for infill. 
    
Notes
-----
Let :math:`\inputRV_1, \dots, \inputRV_N` the samples of dimension :math:`\inputDim` generated by the simulation algorithm, :math:`T` the event threshold and :math:`\widehat{\model}(\cdot)` the mean of the conditioned Gaussian process. The selected samples for infill criterion evaluation are selected according to a criterion based on the quantile of the samples formed by the scaled outputs, given by :math:`\left\{\forall i \in \left\{1, \dots, N\right\} |\widehat{\model}(\inputRV_i) - T|\right\}`.
Let :math:`\vect{X}_{{DOE}_1}, \dots, \vect{X}_{{DOE}_n}` the current input Design of Experiments.
Let consider :math:`\vect{X}_i` a sample selected for infill criterion evaluation and math:`f_{\inputRV}(\vect{X}_i)` the value of the input vector PDF on the selected sample. The Generalized Max Min (GMM) function  :math:`GMM: \Rset^{\inputDim} \rightarrow \Rset^{+}` is defined as the minimal distance to the DoE weighted by the PDF of the input vector:

.. math::
   :nowrap:
   
   GMM(\vect{X}_i)=`f_{\inputRV}(\vect{X}_i)^{1/d} \min_{j=1,...,n} \|\inputRV_i - \vect{X}_{{DOE}_j}\|

The sample that maximizes the GMM criterion will be selected for infill.
)RAW"
